---
version: "3"
services:
  idp:
    build:
      context: .
      dockerfile: test_files/idp/Dockerfile
  sp:
    build:
      context: .
      dockerfile: test_files/sp/Dockerfile
    depends_on:
      - "idp"
  client:
    build:
      context: .
      dockerfile: test_files/client/Dockerfile
    depends_on:
      - "sp"
